"""empty message

Revision ID: 2cf08c522bb4
Revises: a36d80b15fab
Create Date: 2020-04-09 14:00:08.065891

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '2cf08c522bb4'
down_revision = 'a36d80b15fab'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_index(op.f('ix_tracks_user_id'), table_name='tracks')
    op.alter_column('tracks', 'user_id', existing_type=sa.String(length=60), nullable=False)
    op.create_index(op.f('ix_tracks_user_id'), 'tracks', ['user_id'], unique=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('contact_user_id', sa.String(length=60), nullable=False),
    sa.Column('geo_point', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('contact_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_contact_user_id'), 'contacts', ['contact_user_id'], unique=False)
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_contact_user_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
