"""Migration message

Revision ID: a36d80b15fab
Revises:
Create Date: 2020-03-27 23:14:57.088570

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'a36d80b15fab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger, nullable=False, index=True),
    sa.Column('geo_points', geoalchemy2.types.Geometry(geometry_type='MultiPointZ'), nullable=True),
    sa.Column('health_status', sa.Enum('healthy', 'feel_sick', 'covid_confirmed', name='health_status_enum'), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    op.execute('DROP TYPE health_status_enum')
    # ### end Alembic commands ###
