"""empty message

Revision ID: ab3499ef1852
Revises:
Create Date: 2020-04-14 18:41:55.799332

"""
from alembic import op
import sqlalchemy as sa

import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'ab3499ef1852'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keys',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_key', sa.String(length=80), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geo_boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('anon_user_key', sa.String(length=80), nullable=False),
    sa.Column('geo_points', geoalchemy2.types.Geometry(geometry_type='MULTIPOINTZ'), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geo_boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    op.drop_table('keys')
    op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###
