"""empty message

Revision ID: d1a21235fe77
Revises: ab3499ef1852
Create Date: 2020-04-30 17:48:26.637276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a21235fe77'
down_revision = 'ab3499ef1852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keys', sa.Column('meta', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keys', 'meta')
    # ### end Alembic commands ###
